spring.application.name=concept01
PaymentGateway.type= phone pay
PaymentGateway.retryCount= 8

#-----------------------------------------------
User.name = sharwan
User.age = 22

#-------------------------------------------------
user-properties.name = Mahakal
user-properties.age = 100