spring.application.name=CrudWithJPA

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


#Most important
#ddl-auto=update → automatically creates/updates tables
#show-sql=true → prints SQL queries
#format_sql=true → formats SQL nicely
#hibernate.SQL=DEBUG → detailed SQL logging
#jdbc.bind=TRACE → shows actual values passed to ?